[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.54"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.54"

